version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "github-actions"
    # Workflow files in .github/workflows will be checked
    directory: "/"
    schedule:
      interval: "daily"
