name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust Cargo project CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo format
        run: cargo fmt --all -- --check

      - name: Cargo test (default features)
        run: cargo test

      - name: Cargo test (all features)
        run: cargo test --all-features

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features

      - name: Cargo release + all feature build
        run: cargo build --release --all-features
