name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust project testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: fmt

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
