name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust Cargo project CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Cargo release + all feature build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
